@startuml

title Usecase for Information system

' left to right direction

actor Адміністратор
actor Робітник


Адміністратор -|> Робітник 

rectangle Software {

    usecase (Створити форму для підписів)
    usecase (Поставити підпис)
    usecase (Авторизуватися)
    
    (Поставити підпис) .> (Авторизуватися) : include
   

    Адміністратор -- (Створити форму для підписів)
    Робітник -- (Поставити підпис)
    Робітник -- (Авторизуватися)

}

@enduml
